###
GET https://localhost:8080/api/companies
Content-Type: application/json

###
POST https://localhost:8080/api/companies/add
Content-Type: application/json

  {
    "ein_tin": "38-1234567",
    "name": "new test"
  }

###
PUT https://localhost:8080/api/companies/update
Content-Type: application/json

  {
    "ein_tin": "38-1234567",
    "name": "update",
    "active": "0"
  }
