###
GET https://localhost:8080/api/companies
Content-Type: application/json

###
# Causes application to crash if ran twice
# Could be the active being passed when not included
# in the addCompany function in the model
POST https://localhost:8080/api/companies/create
Content-Type: application/json

  {
    "ein_tin": "38-1234567",
    "name": "new test",
  }

###
PUT https://localhost:8080/api/companies/update
Content-Type: application/json

  {
    "ein_tin": "38-1234567",
    "name": "update",
    "active": "0"
  }
