###
GET https://localhost:8080/api/tickets
Content-Type: application/json

###
GET https://localhost:8080/api/tickets/3
Content-Type: application/json

###
GET https://localhost:8080/api/tickets/2
Content-Type: application/json

###
# Doesn't crash like companies/create
POST https://localhost:8080/api/tickets/
Content-Type: application/json

{
  "company_id": "40-2522401",
  "engineer_id": 3, 
  "title": "test title",
  "status": "Open",
  "owner_id": "11eeb505-16a3-6017-8584-001fbc130d5b"
}

###
PUT https://localhost:8080/api/tickets/update
Content-Type: application/json

{
  "id": "2",
  "title": "UPDATE IS WORKING",
  "status": "Closed"
}
